name: Build RustOwl

on:
  push:
    branches: ["main"]
  pull_request:
    types: ["labeled"]
  workflow_dispatch:
  workflow_call:
    outputs:
      run_id:
        description: Run ID of this workflow
        value: ${{ github.run_id }}

jobs:
  build:
    if: github.event.action != 'labeled' || github.event.label.name == 'do-build-check'
    strategy:
      matrix:
        os:
          [
            ubuntu-24.04,
            ubuntu-24.04-arm,
            macos-15,
            macos-13,
            windows-2022,
            windows-11-arm,
          ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Install Nushell
        uses: hustcer/setup-nu@v3
        with:
          version: "0.100.0"

      - name: Install Rust toolchain
        run: rustup show

      - name: Build and package
        run: nu installation/source/build.nu --profile release --output-dir dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: rustowl-${{ matrix.os }}
          path: dist/*

  vscode:
    if: github.event.action != 'labeled' || github.event.label.name == 'do-build-check'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: ./editors/vscode/package.json
          run_install: |
            - cwd: ./editors/vscode

      - name: Build VSIX
        run: pnpm build
        working-directory: ./editors/vscode

      - uses: actions/upload-artifact@v5
        with:
          name: rustowl-vscode
          path: editors/vscode/**/*.vsix
