name: Release RustOwl

on:
  push:
    tags:
      - v*

permissions:
  actions: read
  contents: write

jobs:
  check:
    uses: ./.github/workflows/ci.yml
  build:
    uses: ./.github/workflows/build.yaml

  meta:
    name: Check Version
    runs-on: ubuntu-latest
    outputs:
      pre_release: ${{ steps.pre-release.outputs.pre_release }}
    needs:
      - check
      - build
    steps:
      - name: Check pre-release
        id: pre-release
        run: |
          if [[ "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "pre_release=false" >> $GITHUB_OUTPUT
          else
            echo "pre_release=true" >> $GITHUB_OUTPUT
          fi

  crates-io-release:
    name: Create Crates.io release
    runs-on: ubuntu-latest
    needs: ["meta"]
    steps:
      - uses: actions/checkout@v6
      - name: Release crates.io
        if: needs.meta.outputs.pre_release != 'true'
        run: |
          echo '${{ secrets.CRATES_IO_API_TOKEN }}' | cargo login
          cargo publish

  vscode-release:
    name: Create Vscode Release
    runs-on: ubuntu-latest
    needs: ["meta"]
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Setup PNPM And Install dependencies
        if: needs.meta.outputs.pre_release != 'true'
        uses: pnpm/action-setup@v4
        with:
          package_json_file: ./editors/vscode/package.json
          run_install: |
            - cwd: ./editors/vscode
      - name: Release vsce
        if: needs.meta.outputs.pre_release != 'true'
        run: |
          pnpm vsce publish
        working-directory: ./editors/vscode
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

  vscodium-release:
    name: Create Vscodium Release
    runs-on: ubuntu-latest
    needs: ["meta"]
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Setup PNPM And Install dependencies
        if: needs.meta.outputs.pre_release != 'true'
        uses: pnpm/action-setup@v4
        with:
          package_json_file: ./editors/vscode/package.json
          run_install: |
            - cwd: ./editors/vscode
      - name: Release ovsx
        if: needs.meta.outputs.pre_release != 'true'
        run: |
          pnpm ovsx publish
        working-directory: ./editors/vscode
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}

  winget-release:
    name: Create Winget Release
    runs-on: windows-latest
    needs: ["meta"]
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        if: needs.meta.outputs.pre_release != 'true'
        with:
          identifier: Cordx56.Rustowl
          token: ${{ secrets.WINGET_TOKEN }}

  aur-release:
    name: Create AUR Release
    runs-on: ubuntu-latest
    needs: ["meta"]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: AUR Release
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        if: needs.meta.outputs.pre_release != 'true'
        with:
          pkgname: rustowl
          pkgbuild: ./packages/aur/PKGBUILD
          updpkgsums: true
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,ecdsa,ed25519
        env:
          AUR_USERNAME: ${{ secrets.AUR_USERNAME }}
          AUR_EMAIL: ${{ secrets.AUR_EMAIL }}
          AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
      - name: AUR Release (Bin)
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        if: needs.meta.outputs.pre_release != 'true'
        with:
          pkgname: rustowl-bin
          pkgbuild: ./packages/aur/PKGBUILD-BIN
          updpkgsums: true
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,ecdsa,ed25519
        env:
          AUR_USERNAME: ${{ secrets.AUR_USERNAME }}
          AUR_EMAIL: ${{ secrets.AUR_EMAIL }}
          AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}

  github-release:
    name: Create A GitHub Release
    runs-on: ubuntu-latest
    needs: ["meta"]
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Generate Release Notes
        run: |
          npx changelogithub@latest --contributors --output release.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download All Artifacts
        uses: actions/download-artifact@v6
        with:
          path: artifacts
          pattern: rustowl-*
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          draft: true
          body_path: release.md
          prerelease: ${{ needs.meta.outputs.pre_release == 'true' }}

  docker-release:
    name: Release To GitHub Container Registry
    runs-on: ubuntu-latest
    needs: ["meta"]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: packages/docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
